// Generated protobuf source file
// This is a placeholder - needs to be generated from heartbeat.proto
// Location: Leapfrog_FlightController/heartbeat.pb.cc

#include "heartbeat.pb.h"

// This file should be generated by running:
// protoc --cpp_out=. heartbeat.proto
