// Generated protobuf header file
// This is a placeholder - needs to be generated from heartbeat.proto
// Location: Leapfrog_FlightController/heartbeat.pb.h

#ifndef HEARTBEAT_PB_H
#define HEARTBEAT_PB_H

// This file should be generated by running:
// protoc --cpp_out=. heartbeat.proto

#endif // HEARTBEAT_PB_H
