acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=55
45
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=20
80
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=24
76
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=29
71
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=12
88
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=44
56
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=83
17
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=57
43
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=37
63
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=66
34
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=66
34
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=90
10
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=73
27
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=74
26
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=100
0
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
acs fire p=0
100
